/** Eine vollständige, gültige Eingabe des Assistenten. */
export const VALID_LISTING = {
  category: 'CAR',
  brandSlug: 'volkswagen',
  modelSlug: 'passat',
  variant: '2.0 TDI',
  registrationYear: 2017,
  registrationMonth: 6,
  mileageKm: 168000,
  fuel: 'DIESEL',
  transmission: 'AUTOMATIC',
  powerKw: 110,
  bodyType: 'ESTATE',
  driveType: 'FWD',
  doors: 5,
  seats: 5,
  color: 'grey',
  interiorColor: 'black',
  emissionClass: 'EURO_6',
  condition: 'USED',
  accidentFree: true,
  serviceHistory: true,
  customsStatus: 'CLEARED',
  plateOrigin: 'RKS',
  importedFromCode: 'DE',
  steeringSide: 'LEFT',
  features: ['navigation', 'parking-sensors', 'heated-seats'],
  images: [
    { key: 'test/a.jpg', url: '/uploads/test/a.jpg' },
    { key: 'test/b.jpg', url: '/uploads/test/b.jpg' },
  ],
  priceEur: 12500,
  negotiable: true,
  citySlug: 'prishtine',
  postalCode: '10000',
  hideExactAddress: true,
  description:
    'Volkswagen Passat 2.0 TDI, viti 2017, i doganuar plotësisht dhe me libër servisi të plotë. Gjendja teknike është e shkëlqyer.',
} as const;
